[remote.github]
owner = "cuervolu"
repo = "wn"

[changelog]
header = """
# Registro de cambios

Acá están todos los cambios importantes del proyecto, mi chanchito.

El formato está basado en [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
y este proyecto sigue [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
"""

body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}]\
    {% if previous.version %} - {{ timestamp | date(format="%Y-%m-%d") }}{% endif %}

{% else %}\
    ## [No publicado]

{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}\
    - {{ commit.message | upper_first }}\
    {% if commit.github.username %} por @{{ commit.github.username }}{% endif %}\
    {% if commit.github.pr_number %} ([#{{ commit.github.pr_number }}](https://github.com/cuervolu/wn/pull/{{ commit.github.pr_number }})){% endif %}
{% endfor %}
{% endfor %}\n
"""

footer = """
{% for release in releases %}\
    {% if release.version %}\
        {% if release.previous.version %}\
            [{{ release.version | trim_start_matches(pat="v") }}]: \
                https://github.com/cuervolu/wn/compare/{{ release.previous.version }}..{{ release.version }}
        {% endif %}\
    {% else %}\
        [unreleased]: https://github.com/cuervolu/wn/compare/\
            {% if releases | length > 1 %}\
                {{ releases | nth(n=1) | get(key="version") }}\
            {% endif %}..HEAD
    {% endif %}\
{% endfor %}
<!-- generado por git-cliff -->
"""

trim = true
render_always = true

[git]
conventional_commits = true
filter_unconventional = true
require_conventional = false
split_commits = false
protect_breaking_commits = false
filter_commits = false
topo_order = false
topo_order_commits = true
sort_commits = "oldest"
tag_pattern = "v[0-9]+\\.[0-9]+\\.[0-9]+"

commit_parsers = [
    { message = "^feat", group = "Agregado" },
    { message = "^refactor", group = "Cambiado" },
    { message = "^perf", group = "Cambiado" },
    { message = "^style", group = "Cambiado" },
    { message = "^fix", group = "Arreglado" },
    { body = ".*security", group = "Seguridad" },
    { message = "^security", group = "Seguridad" },
    { message = "^deprecat", group = "Obsoleto" },
    { message = "^remove|^revert", group = "Eliminado" },
    { message = "^chore\\(release\\)", skip = true },
    { message = "^chore\\(deps", skip = true },
    { message = "^chore\\(pr\\)", skip = true },
    { message = "^chore\\(pull\\)", skip = true },
    { message = "^Merge", skip = true },
    { message = "^wip", skip = true },
    { message = "^doc", group = "Misceláneos" },
    { message = "^test", group = "Misceláneos" },
    { message = "^chore|^ci|^build", group = "Misceláneos" },
]

commit_preprocessors = [
    { pattern = "Actualizar pipeline de release a WN\\+\\+", replace = "Actualizar flujo de publicación a WN++" },
    { pattern = "Impedir redeclaración de constantes duro en el mismo scope", replace = "Impedir redeclaración de constantes duro en el mismo alcance" },
    { pattern = "Actualizar la configuración de release", replace = "Actualizar la configuración de publicación" },
    { pattern = "Agregar plantilla para pull requests", replace = "Agregar plantilla para PR" },
    { pattern = "Agregar configuración de CI para formateo, linting y pruebas", replace = "Agregar configuración de CI para formateo, análisis estático y pruebas" },
    { pattern = "Actualizar installers y templates a WN\\+\\+", replace = "Actualizar instaladores y plantillas a WN++" },
    { pattern = "Actualizar el formato y el contenido del changelog", replace = "Actualizar el formato y el contenido del registro de cambios" },
    { pattern = "Se agrega roadmap de piola", replace = "Agregar hoja de ruta de Piola" },
    { pattern = "Add control flow, error handling, functions, data types, and variables documentation", replace = "Agregar documentación de control de flujo, manejo de errores, funciones, tipos de datos y variables" },
    { pattern = "Add release helper script", replace = "Agregar script auxiliar para publicaciones" },
    { pattern = "Update README with installation instructions for macOS, Linux, and Windows", replace = "Actualizar README con instrucciones de instalación para macOS, Linux y Windows" },
    { pattern = "Update Node.js version in docs deployment workflow", replace = "Actualizar versión de Node.js en el flujo de despliegue de documentación" },
    { pattern = "Fix ci", replace = "Corregir CI" },
    { pattern = "Add MIT License file", replace = "Agregar archivo de licencia MIT" },
    { pattern = "Add control flow statements 'devolver', 'cortala', and 'sigue' with error handling", replace = "Agregar sentencias de control de flujo 'devolver', 'cortala' y 'sigue' con manejo de errores" },
    { pattern = "Add self-update command \\(piola update\\)", replace = "Agregar comando de actualización automática (piola update)" },
    { pattern = "Rename binary from piola-cli to piola", replace = "Renombrar binario de piola-cli a piola" },
    { pattern = "Add Cross.toml for OpenSSL in aarch64 cross-compilation", replace = "Agregar Cross.toml para OpenSSL en compilación cruzada a aarch64" },
    { pattern = "Add miette and improve repl", replace = "Agregar miette y mejorar el REPL" },
    { pattern = "Add initial documentation and philosophy for Piola language", replace = "Agregar documentación inicial y filosofía del lenguaje Piola" },
    { pattern = "Add feature design document for Piola language", replace = "Agregar documento de diseño de funcionalidades para el lenguaje Piola" },
    { pattern = "Add release CI workflow", replace = "Agregar flujo de CI para publicaciones" },
    { pattern = "Add cliff.toml for changelog generation", replace = "Agregar cliff.toml para generar el registro de cambios" },
]
